spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/connect
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 9b22077ea2e868fd4684
            clientSecret: fc309e704992dd9bac3877ee563f8241045359c8
            scope:
              - user:email
              - read:user
          google:
            clientId: 358853118375-4crvhc5fo1bql2mk33h21olqutq1fjeb.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          onelogin:
            clientId: 7946e770-10b3-013a-4779-026763a06a77198622
            clientSecret: 9d0bd8d67eb16beeca236dfc8fd4d0498e1eb042c3db0210c76dd1f28cb01282
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - name
        provider:
          onelogin:
            authorizationUri: https://deviknitkkr-dev.onelogin.com/oidc/2/auth
            tokenUri: https://deviknitkkr-dev.onelogin.com/oidc/2/token
            userInfoUri: https://deviknitkkr-dev.onelogin.com/oidc/2/me
            jwkSetUri: https://deviknitkkr-dev.onelogin.com/oidc/2/certs
            userNameAttribute: sub




#issuerUri : http://deviknitkkr-dev.onelogin.com/
#  accessTokenUri: http://deviknitkkr-dev.onelogin.com/oidc/2/token
#  userAuthorizationUri: http://deviknitkkr-dev.onelogin.com/oidc/2/auth
#  tokenName: access_token
#  authorizedGrantTypes: authorization_code
#  resource:
#    userInfoUri: http://deviknitkkr-dev.onelogin.com/oidc/2/me

app:
  jwt-header: Authorization
  jwt-secret: somerandomsecretkey